/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SMOKING_H_RPCGEN
#define _SMOKING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct supplies {
	int tobacco;
	int matches;
	int paper;
};
typedef struct supplies supplies;

#define smoker_problem 87654
#define homework_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_me_my_supply 1
extern  int * get_me_my_supply_1(struct supplies *, CLIENT *);
extern  int * get_me_my_supply_1_svc(struct supplies *, struct svc_req *);
#define stop_service 2
extern  void * stop_service_1(struct supplies *, CLIENT *);
extern  void * stop_service_1_svc(struct supplies *, struct svc_req *);
extern int smoker_problem_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_me_my_supply 1
extern  int * get_me_my_supply_1();
extern  int * get_me_my_supply_1_svc();
#define stop_service 2
extern  void * stop_service_1();
extern  void * stop_service_1_svc();
extern int smoker_problem_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_supplies (XDR *, supplies*);

#else /* K&R C */
extern bool_t xdr_supplies ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SMOKING_H_RPCGEN */
