/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "smoking.h"

bool_t
xdr_supplies (XDR *xdrs, supplies *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tobacco))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->matches))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->paper))
		 return FALSE;
	return TRUE;
}
